"""End-to-end launch for the Aesir RL stack.

Brings up, in dependency order:

    A. robot_state_publisher    (xacro -> URDF, /tf, /tf_static)
    B. mujoco_ros2_control      (physics + ros2_control hardware bridge,
                                 headless -- no built-in viewer)
    C. controller spawners      (joint_state_broadcaster,
                                 joint_group_velocity_controller for the arm,
                                 diff_drive_controller for the base,
                                 flipper_controller)
    D. moveit_servo             (TwistStamped @ /servo_node/delta_twist_cmds
                                 -> Float64MultiArray @
                                 /joint_group_velocity_controller/commands)
    E. rl_agent_env.rl_env      (the Python RL environment node)

Run:
    ros2 launch rl_agent_env train_agents.launch.py
    ros2 launch rl_agent_env train_agents.launch.py mujoco_scene:=/abs/path.xml
"""
from launch import LaunchDescription
from launch.actions import (
    DeclareLaunchArgument,
    ExecuteProcess,
    IncludeLaunchDescription,
    LogInfo,
    RegisterEventHandler,
)
from launch.event_handlers import OnProcessExit
from launch.substitutions import (
    Command,
    FindExecutable,
    LaunchConfiguration,
    PathJoinSubstitution,
)
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description() -> LaunchDescription:
    # ----------------------------------------------------------------- #
    #                       Launch arguments                            #
    # ----------------------------------------------------------------- #
    use_sim_time_arg = DeclareLaunchArgument(
        "use_sim_time", default_value="true",
        description="Track /clock published by MuJoCo (true) or wall clock.",
    )
    log_level_arg = DeclareLaunchArgument(
        "log_level", default_value="info",
        description="rclcpp/rclpy log level.",
    )
    mujoco_scene_arg = DeclareLaunchArgument(
        "mujoco_scene",
        default_value=PathJoinSubstitution([
            FindPackageShare("aesir_robot_description"),
            "worlds", "aesir_scene.xml",
        ]),
        description="Absolute path to the MuJoCo MJCF/XML scene file. "
                    "Defaults to the bundled aesir_robot_description/worlds/"
                    "aesir_scene.xml installed by ament.",
    )

    use_sim_time = LaunchConfiguration("use_sim_time")
    log_level    = LaunchConfiguration("log_level")
    mujoco_scene = LaunchConfiguration("mujoco_scene")

    # ----------------------------------------------------------------- #
    #                Shared resource paths                              #
    # ----------------------------------------------------------------- #
    moveit_cfg_share = FindPackageShare("robot_moveit_config")

    urdf_xacro = PathJoinSubstitution(
        [moveit_cfg_share, "config", "rescue_robot.urdf.xacro"]
    )
    srdf_path = PathJoinSubstitution(
        [moveit_cfg_share, "config", "rescue_robot.srdf"]
    )
    kinematics_yaml = PathJoinSubstitution(
        [moveit_cfg_share, "config", "kinematics.yaml"]
    )
    joint_limits_yaml = PathJoinSubstitution(
        [moveit_cfg_share, "config", "joint_limits.yaml"]
    )
    servo_yaml = PathJoinSubstitution(
        [moveit_cfg_share, "config", "servo_params.yaml"]
    )
    controllers_yaml = PathJoinSubstitution(
        [moveit_cfg_share, "config", "ros2_controllers.yaml"]
    )

    # robot_description is generated by running xacro at launch time.
    robot_description_content = Command([
        FindExecutable(name="xacro"), " ", urdf_xacro,
    ])
    robot_description = {"robot_description": robot_description_content}

    # SRDF and kinematics need to be read as plain text dicts.
    # Use moveit_configs_utils for a cleaner alternative once you migrate;
    # the lightweight build below keeps the launch self-contained.
    robot_description_semantic = {
        "robot_description_semantic":
            Command([FindExecutable(name="cat"), " ", srdf_path]),
    }
    robot_description_kinematics = {
        "robot_description_kinematics":
            # Load kinematics yaml verbatim as a parameter group.
            kinematics_yaml,
    }

    # ----------------------------------------------------------------- #
    #  A. robot_state_publisher                                         #
    # ----------------------------------------------------------------- #
    rsp_node = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        output="screen",
        parameters=[robot_description, {"use_sim_time": use_sim_time}],
    )

    # ----------------------------------------------------------------- #
    #  B. mujoco_ros2_control (headless)                                #
    # ----------------------------------------------------------------- #
    # The mujoco_ros2_control node loads the URDF (with its <ros2_control>
    # block + MujocoSystem plugin), reads the .xml scene, and exposes the
    # controller_manager on /controller_manager. It also publishes /clock.
    mujoco_node = Node(
        package="mujoco_ros2_control",
        executable="mujoco_ros2_control",
        name="mujoco_ros2_control",
        output="screen",
        parameters=[
            robot_description,
            controllers_yaml,
            {"mujoco_model_path": mujoco_scene},
            {"use_sim_time": use_sim_time},
            # Headless: do not open the built-in MuJoCo viewer.
            {"headless": True},
        ],
        arguments=["--ros-args", "--log-level", log_level],
    )

    # ----------------------------------------------------------------- #
    #  C. controller spawners                                           #
    #     Sequenced via OnProcessExit so the controller_manager has time
    #     to come up before each spawner asks for activation.           #
    # ----------------------------------------------------------------- #
    jsb_spawner = Node(
        package="controller_manager", executable="spawner",
        arguments=["joint_state_broadcaster",
                   "--controller-manager", "/controller_manager"],
        output="screen",
    )
    arm_spawner = Node(
        package="controller_manager", executable="spawner",
        arguments=["joint_group_velocity_controller",
                   "--controller-manager", "/controller_manager"],
        output="screen",
    )
    diff_drive_spawner = Node(
        package="controller_manager", executable="spawner",
        arguments=["diff_drive_controller",
                   "--controller-manager", "/controller_manager"],
        output="screen",
    )
    flipper_spawner = Node(
        package="controller_manager", executable="spawner",
        arguments=["flipper_controller",
                   "--controller-manager", "/controller_manager"],
        output="screen",
    )

    spawn_jsb_after_mujoco = RegisterEventHandler(
        OnProcessExit(target_action=mujoco_node, on_exit=[]),  # no-op shutdown handler
    )
    # Proper sequencing: spawn the broadcaster first, then the rest in
    # parallel once it exits successfully.
    spawn_rest_after_jsb = RegisterEventHandler(
        OnProcessExit(
            target_action=jsb_spawner,
            on_exit=[arm_spawner, diff_drive_spawner, flipper_spawner],
        )
    )

    # ----------------------------------------------------------------- #
    #  D. moveit_servo                                                  #
    # ----------------------------------------------------------------- #
    # Servo needs: servo_params + robot_description + SRDF + kinematics
    # + joint_limits. All passed as parameter dicts/files.
    servo_node = Node(
        package="moveit_servo",
        executable="servo_node_main",  # On older distros: "servo_server"
        name="servo_node",
        output="screen",
        parameters=[
            servo_yaml,
            robot_description,
            robot_description_semantic,
            kinematics_yaml,
            joint_limits_yaml,
            {"use_sim_time": use_sim_time},
        ],
    )

    # Wait until at least the arm controller is up before starting Servo,
    # otherwise the first Servo commands hit a non-existent controller.
    start_servo_after_arm = RegisterEventHandler(
        OnProcessExit(target_action=arm_spawner, on_exit=[servo_node])
    )

    # ----------------------------------------------------------------- #
    #  E. RL environment (Python -- owns rclpy spin + PPO)              #
    # ----------------------------------------------------------------- #
    rl_env_node = Node(
        package="rl_agent_env",
        executable="rl_env",
        name="rl_communication_bridge",
        output="screen",
        emulate_tty=True,
        parameters=[{"use_sim_time": use_sim_time}],
        arguments=["--ros-args", "--log-level", log_level],
    )
    # Launch the RL env only after Servo is up -- the env immediately
    # starts publishing TwistStamped on /servo_node/delta_twist_cmds.
    start_rl_env_after_servo = RegisterEventHandler(
        OnProcessExit(target_action=arm_spawner, on_exit=[rl_env_node])
    )

    # ----------------------------------------------------------------- #
    return LaunchDescription([
        # args
        use_sim_time_arg, log_level_arg, mujoco_scene_arg,
        LogInfo(msg=["[rl_agent_env] Launching Aesir end-to-end stack."]),
        # A
        rsp_node,
        # B
        mujoco_node,
        # C (spawners + their sequencing)
        jsb_spawner,
        spawn_jsb_after_mujoco,
        spawn_rest_after_jsb,
        # D
        start_servo_after_arm,
        # E
        start_rl_env_after_servo,
    ])
